export const ClaseAccion = {
    CAMBIAR_COLOR: "CAMBIAR-COLOR",
    AJUSTAR_LIENZO: "AJUSTAR-LIENZO",
    NUEVA_CAPA: "NUEVA-CAPA",
    ELIMINAR_CAPA: "ELIMINAR-CAPA",
    ACTUALIZAR_PIXEL: "ACTUALIZAR-PIXEL",
    DESHACER_PIXEL: "DESHACER-PIXEL",
    ACTIVAR_CAPA: "ACTIVAR-CAPA",
    MOSTRAR_MENSAJE: "MOSTRAR-MENSAJE",
    QUITAR_MENSAJE: "QUITAR-MENSAJE",
    NUEVO_PROYECTO: "NUEVO-PROYECTO",
    REDIMENSIONAR_LIENZO: "REDIMENSIONAR-LIENZO",
    ESTA_PINTANDO: "ESTA-PINTANDO",
    DESHACER: "DESHACER"
}